//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdmin.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        WebAdmin.Service.CheckLoginResponse CheckLogin(WebAdmin.Service.CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.CheckLoginResponse> CheckLoginAsync(WebAdmin.Service.CheckLoginRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        WebAdmin.Service.ChangePasswordResponse ChangePassword(WebAdmin.Service.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.ChangePasswordResponse> ChangePasswordAsync(WebAdmin.Service.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetArticleDetailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArticleDetail", ReplyAction="*")]
        WebAdmin.Service.GetArticleDetailResponse GetArticleDetail(WebAdmin.Service.GetArticleDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArticleDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.GetArticleDetailResponse> GetArticleDetailAsync(WebAdmin.Service.GetArticleDetailRequest request);
        
        // CODEGEN: Generating message contract since element name GetArticleListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArticleList", ReplyAction="*")]
        WebAdmin.Service.GetArticleListResponse GetArticleList(WebAdmin.Service.GetArticleListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArticleList", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.GetArticleListResponse> GetArticleListAsync(WebAdmin.Service.GetArticleListRequest request);
        
        // CODEGEN: Generating message contract since element name itemJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddArticle", ReplyAction="*")]
        WebAdmin.Service.AddArticleResponse AddArticle(WebAdmin.Service.AddArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddArticle", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.AddArticleResponse> AddArticleAsync(WebAdmin.Service.AddArticleRequest request);
        
        // CODEGEN: Generating message contract since element name itemJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UdateArticle", ReplyAction="*")]
        WebAdmin.Service.UdateArticleResponse UdateArticle(WebAdmin.Service.UdateArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UdateArticle", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAdmin.Service.UdateArticleResponse> UdateArticleAsync(WebAdmin.Service.UdateArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveArticle", ReplyAction="*")]
        bool RemoveArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveArticle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveArticleAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLogin", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.CheckLoginRequestBody Body;
        
        public CheckLoginRequest() {
        }
        
        public CheckLoginRequest(WebAdmin.Service.CheckLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        public CheckLoginRequestBody() {
        }
        
        public CheckLoginRequestBody(string userName, string passWord) {
            this.userName = userName;
            this.passWord = passWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.CheckLoginResponseBody Body;
        
        public CheckLoginResponse() {
        }
        
        public CheckLoginResponse(WebAdmin.Service.CheckLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckLoginResult;
        
        public CheckLoginResponseBody() {
        }
        
        public CheckLoginResponseBody(bool CheckLoginResult) {
            this.CheckLoginResult = CheckLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(WebAdmin.Service.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string userName, string oldPassword, string newPassword) {
            this.userName = userName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(WebAdmin.Service.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticleDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticleDetail", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.GetArticleDetailRequestBody Body;
        
        public GetArticleDetailRequest() {
        }
        
        public GetArticleDetailRequest(WebAdmin.Service.GetArticleDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArticleDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public GetArticleDetailRequestBody() {
        }
        
        public GetArticleDetailRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticleDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticleDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.GetArticleDetailResponseBody Body;
        
        public GetArticleDetailResponse() {
        }
        
        public GetArticleDetailResponse(WebAdmin.Service.GetArticleDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArticleDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetArticleDetailResult;
        
        public GetArticleDetailResponseBody() {
        }
        
        public GetArticleDetailResponseBody(string GetArticleDetailResult) {
            this.GetArticleDetailResult = GetArticleDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticleListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticleList", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.GetArticleListRequestBody Body;
        
        public GetArticleListRequest() {
        }
        
        public GetArticleListRequest(WebAdmin.Service.GetArticleListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArticleListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        public GetArticleListRequestBody() {
        }
        
        public GetArticleListRequestBody(int page, int pageSize) {
            this.page = page;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticleListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticleListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.GetArticleListResponseBody Body;
        
        public GetArticleListResponse() {
        }
        
        public GetArticleListResponse(WebAdmin.Service.GetArticleListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArticleListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetArticleListResult;
        
        public GetArticleListResponseBody() {
        }
        
        public GetArticleListResponseBody(string GetArticleListResult) {
            this.GetArticleListResult = GetArticleListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddArticle", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.AddArticleRequestBody Body;
        
        public AddArticleRequest() {
        }
        
        public AddArticleRequest(WebAdmin.Service.AddArticleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddArticleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemJson;
        
        public AddArticleRequestBody() {
        }
        
        public AddArticleRequestBody(string itemJson) {
            this.itemJson = itemJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddArticleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.AddArticleResponseBody Body;
        
        public AddArticleResponse() {
        }
        
        public AddArticleResponse(WebAdmin.Service.AddArticleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddArticleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddArticleResult;
        
        public AddArticleResponseBody() {
        }
        
        public AddArticleResponseBody(bool AddArticleResult) {
            this.AddArticleResult = AddArticleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UdateArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UdateArticle", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.UdateArticleRequestBody Body;
        
        public UdateArticleRequest() {
        }
        
        public UdateArticleRequest(WebAdmin.Service.UdateArticleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UdateArticleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemJson;
        
        public UdateArticleRequestBody() {
        }
        
        public UdateArticleRequestBody(string itemJson) {
            this.itemJson = itemJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UdateArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UdateArticleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAdmin.Service.UdateArticleResponseBody Body;
        
        public UdateArticleResponse() {
        }
        
        public UdateArticleResponse(WebAdmin.Service.UdateArticleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UdateArticleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UdateArticleResult;
        
        public UdateArticleResponseBody() {
        }
        
        public UdateArticleResponseBody(bool UdateArticleResult) {
            this.UdateArticleResult = UdateArticleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebAdmin.Service.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebAdmin.Service.WebServiceSoap>, WebAdmin.Service.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.CheckLoginResponse WebAdmin.Service.WebServiceSoap.CheckLogin(WebAdmin.Service.CheckLoginRequest request) {
            return base.Channel.CheckLogin(request);
        }
        
        public bool CheckLogin(string userName, string passWord) {
            WebAdmin.Service.CheckLoginRequest inValue = new WebAdmin.Service.CheckLoginRequest();
            inValue.Body = new WebAdmin.Service.CheckLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            WebAdmin.Service.CheckLoginResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).CheckLogin(inValue);
            return retVal.Body.CheckLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.CheckLoginResponse> WebAdmin.Service.WebServiceSoap.CheckLoginAsync(WebAdmin.Service.CheckLoginRequest request) {
            return base.Channel.CheckLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.CheckLoginResponse> CheckLoginAsync(string userName, string passWord) {
            WebAdmin.Service.CheckLoginRequest inValue = new WebAdmin.Service.CheckLoginRequest();
            inValue.Body = new WebAdmin.Service.CheckLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            return ((WebAdmin.Service.WebServiceSoap)(this)).CheckLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.ChangePasswordResponse WebAdmin.Service.WebServiceSoap.ChangePassword(WebAdmin.Service.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string userName, string oldPassword, string newPassword) {
            WebAdmin.Service.ChangePasswordRequest inValue = new WebAdmin.Service.ChangePasswordRequest();
            inValue.Body = new WebAdmin.Service.ChangePasswordRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            WebAdmin.Service.ChangePasswordResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.ChangePasswordResponse> WebAdmin.Service.WebServiceSoap.ChangePasswordAsync(WebAdmin.Service.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.ChangePasswordResponse> ChangePasswordAsync(string userName, string oldPassword, string newPassword) {
            WebAdmin.Service.ChangePasswordRequest inValue = new WebAdmin.Service.ChangePasswordRequest();
            inValue.Body = new WebAdmin.Service.ChangePasswordRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((WebAdmin.Service.WebServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.GetArticleDetailResponse WebAdmin.Service.WebServiceSoap.GetArticleDetail(WebAdmin.Service.GetArticleDetailRequest request) {
            return base.Channel.GetArticleDetail(request);
        }
        
        public string GetArticleDetail(int ID) {
            WebAdmin.Service.GetArticleDetailRequest inValue = new WebAdmin.Service.GetArticleDetailRequest();
            inValue.Body = new WebAdmin.Service.GetArticleDetailRequestBody();
            inValue.Body.ID = ID;
            WebAdmin.Service.GetArticleDetailResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).GetArticleDetail(inValue);
            return retVal.Body.GetArticleDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.GetArticleDetailResponse> WebAdmin.Service.WebServiceSoap.GetArticleDetailAsync(WebAdmin.Service.GetArticleDetailRequest request) {
            return base.Channel.GetArticleDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.GetArticleDetailResponse> GetArticleDetailAsync(int ID) {
            WebAdmin.Service.GetArticleDetailRequest inValue = new WebAdmin.Service.GetArticleDetailRequest();
            inValue.Body = new WebAdmin.Service.GetArticleDetailRequestBody();
            inValue.Body.ID = ID;
            return ((WebAdmin.Service.WebServiceSoap)(this)).GetArticleDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.GetArticleListResponse WebAdmin.Service.WebServiceSoap.GetArticleList(WebAdmin.Service.GetArticleListRequest request) {
            return base.Channel.GetArticleList(request);
        }
        
        public string GetArticleList(int page, int pageSize) {
            WebAdmin.Service.GetArticleListRequest inValue = new WebAdmin.Service.GetArticleListRequest();
            inValue.Body = new WebAdmin.Service.GetArticleListRequestBody();
            inValue.Body.page = page;
            inValue.Body.pageSize = pageSize;
            WebAdmin.Service.GetArticleListResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).GetArticleList(inValue);
            return retVal.Body.GetArticleListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.GetArticleListResponse> WebAdmin.Service.WebServiceSoap.GetArticleListAsync(WebAdmin.Service.GetArticleListRequest request) {
            return base.Channel.GetArticleListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.GetArticleListResponse> GetArticleListAsync(int page, int pageSize) {
            WebAdmin.Service.GetArticleListRequest inValue = new WebAdmin.Service.GetArticleListRequest();
            inValue.Body = new WebAdmin.Service.GetArticleListRequestBody();
            inValue.Body.page = page;
            inValue.Body.pageSize = pageSize;
            return ((WebAdmin.Service.WebServiceSoap)(this)).GetArticleListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.AddArticleResponse WebAdmin.Service.WebServiceSoap.AddArticle(WebAdmin.Service.AddArticleRequest request) {
            return base.Channel.AddArticle(request);
        }
        
        public bool AddArticle(string itemJson) {
            WebAdmin.Service.AddArticleRequest inValue = new WebAdmin.Service.AddArticleRequest();
            inValue.Body = new WebAdmin.Service.AddArticleRequestBody();
            inValue.Body.itemJson = itemJson;
            WebAdmin.Service.AddArticleResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).AddArticle(inValue);
            return retVal.Body.AddArticleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.AddArticleResponse> WebAdmin.Service.WebServiceSoap.AddArticleAsync(WebAdmin.Service.AddArticleRequest request) {
            return base.Channel.AddArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.AddArticleResponse> AddArticleAsync(string itemJson) {
            WebAdmin.Service.AddArticleRequest inValue = new WebAdmin.Service.AddArticleRequest();
            inValue.Body = new WebAdmin.Service.AddArticleRequestBody();
            inValue.Body.itemJson = itemJson;
            return ((WebAdmin.Service.WebServiceSoap)(this)).AddArticleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAdmin.Service.UdateArticleResponse WebAdmin.Service.WebServiceSoap.UdateArticle(WebAdmin.Service.UdateArticleRequest request) {
            return base.Channel.UdateArticle(request);
        }
        
        public bool UdateArticle(string itemJson) {
            WebAdmin.Service.UdateArticleRequest inValue = new WebAdmin.Service.UdateArticleRequest();
            inValue.Body = new WebAdmin.Service.UdateArticleRequestBody();
            inValue.Body.itemJson = itemJson;
            WebAdmin.Service.UdateArticleResponse retVal = ((WebAdmin.Service.WebServiceSoap)(this)).UdateArticle(inValue);
            return retVal.Body.UdateArticleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAdmin.Service.UdateArticleResponse> WebAdmin.Service.WebServiceSoap.UdateArticleAsync(WebAdmin.Service.UdateArticleRequest request) {
            return base.Channel.UdateArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAdmin.Service.UdateArticleResponse> UdateArticleAsync(string itemJson) {
            WebAdmin.Service.UdateArticleRequest inValue = new WebAdmin.Service.UdateArticleRequest();
            inValue.Body = new WebAdmin.Service.UdateArticleRequestBody();
            inValue.Body.itemJson = itemJson;
            return ((WebAdmin.Service.WebServiceSoap)(this)).UdateArticleAsync(inValue);
        }
        
        public bool RemoveArticle(int id) {
            return base.Channel.RemoveArticle(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveArticleAsync(int id) {
            return base.Channel.RemoveArticleAsync(id);
        }
    }
}
